version: '3.8'

services:
  server:
    build:
      context: ./core  # Контекст теперь core директория
      dockerfile: ../docker/core/Dockerfile.dev
    ports:
      - "${HTTP_FORWARD_PORT:-8080}:${HTTP_PORT:-8080}"
    volumes:
      - ./core:/app
      - ./tmp:/app/tmp
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER:-postgres}:${DATABASE_PASSWORD:-postgres}@postgres:5432/${DATABASE_DATABASE:-postgres}?sslmode=disable
    depends_on:
      - postgres
    env_file: .env
    restart: always

  ml-service:
    build:
      context: ./ML
      dockerfile: ../docker/ml/Dockerfile.dev
    volumes:
      - ./ML:/app
      - ./ML/models:/app/models
      - ./ML/catboost_info:/app/catboost_info
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=${DATABASE_DATABASE:-postgres}
      - DATABASE_USER=${DATABASE_USER:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-postgres1}
      - DATABASE_PORT=5432
      - PYTHONPATH=/app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:15-alpine
    ports:
      - ${DATABASE_PORT:-5555}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres1}
      - POSTGRES_DB=${DATABASE_DATABASE:-postgres}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
